### ISSUE TITLE
VisB: after opening new VisB JSON file no visualisation is visible

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#152] opened 2022-06-17 09:12 UTC
After opening new VisB JSON file no visualisation is visible, one has to explicitly press the reload button in ProB2-UI to see the visualisation.

**Comment by favu100** [comment] 2022-06-17 12:23
~~Seems to be an issue that only appears for XTL models~~ This also happens for models other than XTL. The problem is described below

**Comment by favu100** [comment] 2022-06-17 13:11
It seems that the visualization is not updated when the new visualization file is equal to the previous visualization file

**Comment by favu100** [comment] 2022-06-17 13:22
This issue should be fixed now

**Closed as completed by favu100** 2022-06-17 13:22 UTC
Labels: bug, ProB2UI
