### ISSUE TITLE
Issue with ProB Not responding

### ISSUE THREAD

**Issue by shanuka2000** [hhu-stups/prob-issues#265] opened 2023-01-04 21:41 UTC
I am trying to open a .mch file in ProB and as soon as I open the file ProB does not respond. I waited for a long time to see if it will work but it does not.

I have tried troubleshooting the issue and  tried changing the Java version, running the program as administrator but still the issue isn't resolved . 

Also checked the java version and parser version by clicking the button in debug option. It says that the Java version is compatible but the Java B parser was not able to launch. Herewith I will be attaching some screen shots of the issue.

Operating system windows 11
Pro B version 1.8.0-final
Java version 1.8.0

![image](https://user-images.githubusercontent.com/115928935/210654819-2c006c5f-26cf-430f-829e-96217485f34b.png)
![image](https://user-images.githubusercontent.com/115928935/210654961-6d9ff654-0366-4594-a311-45dcdcd63daa.png)

**Comment by iTitus** [comment] 2023-01-05 00:03
probably a duplicate of #264

**Comment by leuschel** [comment] 2023-01-05 09:11
Can you try using ProB 1.11.1 or the latest nightly build (https://prob.hhu.de/w/index.php?title=Download#Nightly_Builds)?
Can you try putting ProB into verbose mode before loading the machine (Sets.mch) by choosing "Debugging Info" in the Debug menu? What happens when you run the command-line version of ProB: ```probcli.exe Sets.mch -init -v```

As suggested above, you can also try "Check Java and Parser Version" in the debug menu. My suspicion, however, is that the Windows firewall is preventing ProB Tcl/Tk to communicate with the Java parser.

**Closed as completed** 2023-02-27 13:41 UTC
Labels: bug, duplicate, ProB Tcl/Tk
