### ISSUE TITLE
Prob B parser can't start with Java 17

### ISSUE THREAD

**Issue by bansan85** [hhu-stups/prob-issues#101] opened 2022-01-09 10:18 UTC
With java 17 from Oracle, I can't use "Debug" > "Check Java and Parser Version". It opens a command line with just a number and ProB freezes.

```
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

But with java 1.8 from OpenJDK, it's a win.

```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

**Comment by leuschel** [comment] 2022-01-09 11:41
Dear Vincent,

which operating system and which version of ProB are you using exactly?
Can you send me a screenshot?

Greetings,
Michael

**Comment by leuschel** [comment] 2022-01-09 17:01
Dear Vincent,, it would be interesting to know whether only the "Check Java and Parser Version" feature is not working, or whether there are other issues (e.g., when parsing / loading B machines).

**Comment by bansan85** [comment] 2022-01-09 17:43
I use ProB 1.11.1.
I have Windows 11 Pro (Version 21H2 build 22000.376)

![image](https://user-images.githubusercontent.com/9248729/148693786-5c1dbebc-c47f-4c7e-b1a4-f5c271fa731a.png)

If I close the Java popup, I have:

```
Unexpected error while parsing machine: 
The Java B parser (probcliparser.jar) cannot be launched:  e:/program files/prob//lib/probcliparser.jar
Please check that Java and B Parser are available using the "Check Java and Parser Version" command in the Debug menu.
```

![image](https://user-images.githubusercontent.com/9248729/148693852-a7f1aed1-1c17-4f17-9b53-890f4ec1ccf0.png)


I have the same java popup/freeze if I try to open a mch file :

![image](https://user-images.githubusercontent.com/9248729/148693915-498d143e-0350-4187-843d-34c584e7ea8a.png)

**Comment by leuschel** [comment] 2022-01-09 18:11
Thanks, can you try running probcli.exe -check_java_version in a Windows shell and give us the output?

**Comment by bansan85** [comment] 2022-01-09 18:45
`probcli.exe` freezes:

```
Result of checking Java version:
  Java is correctly installed and version 1.17.35-LTS-2724"
 is compatible with ProB requirements (>= 1.7).
```

![image](https://user-images.githubusercontent.com/9248729/148696003-b0ba92de-997b-42f6-bd63-631e5246db10.png)

And after manually closing the java popup:

```
Result of checking Java version:
  Java is correctly installed and version 1.17.35-LTS-2724"
 is compatible with ProB requirements (>= 1.7).
←[31m←[1m
! An error occurred (source: parsercall) !
←[0m←[31m←[1m! Unexpected error while parsing machine: ←[0m
←[31m←[1m
! An error occurred (source: parsercall) !
←[0m←[31m←[1m! The Java B parser (probcliparser.jar) cannot be launched:  e:/program files/prob//lib/probcliparser.jar←[0m
←[31m←[1m
! An error occurred (source: parsercall) !
←[0m←[31m←[1m! Please check that Java and B Parser are available, e.g., using "probcli.exe -check_java_version" command.←[0m
←[31m←[1m
! An error occurred (source: check_parser_version) !
←[0m←[31m←[1m! Cannot start Java B Parser to obtain version number←[0m
←[31m←[1m! % *** Errors occurred while loading ! ***←[0m


←[31m←[1m! *** error occurred ***←[0m
←[31m←[1m! parsercall←[0m
←[31m←[1m! *** Occurences of this error: ←[0m
←[31m←[1m! 3←[0m
←[31m←[1m! *** error occurred ***←[0m
←[31m←[1m! check_parser_version←[0m
! Total Errors: 2, Warnings:0
```

Good luck :)

**Comment by leuschel** [comment] 2022-01-10 06:28
Thanks, very strange that there seems to be no Java or Windows error message. The pop-up is also very strange. Have you been able to use this Java version for other software?
How about if you start the probcliparser.jar manually with Java 17, e.g., like this::
```
$ java -jar lib/probcliparser.jar -version
Version:    2.9.32
Git Commit: 7306d13499ba281a6e336c006d9fb23204624daa
```

**Comment by leuschel** [comment] 2022-01-10 09:52
It could be that under Windows 11 the standard output of the Java Parser is sent to a terminal window rather than being sent to ProB.

**Comment by leuschel** [comment] 2022-01-10 11:23
BTW: I have improved the detection of the Java version numbers (the latest Oracle build uses a slightly different format for -fullversion than before). Hence the trailing quotes in the above output (1.17.35-LTS-2724") should now have disappeared in the latest nightly release. However, this does not solve the stdout issue.

**Comment by bansan85** [comment] 2022-01-10 22:02
> Thanks, very strange that there seems to be no Java or Windows error message. The pop-up is also very strange. Have you been able to use this Java version for other software? How about if you start the probcliparser.jar manually with Java 17, e.g., like this::
> 
> ```
> $ java -jar lib/probcliparser.jar -version
> Version:    2.9.32
> Git Commit: 7306d13499ba281a6e336c006d9fb23204624daa
> ```

Interesting... I do not have a problem with `java -jar lib/probcliparser.jar -version`.

```
Version:    2.9.32
Git Commit: 7306d13499ba281a6e336c006d9fb23204624daa
```

I can't try at the moment with a Windows 10. It's a mess, I just uploaded my computer to Windows 11 a few hours before I installed ProB.

I'm pretty sure my java machine works well. But nowadays, every software embeds the java machine so I don't really have a software to test. I can't remember when I installed Java 17. I just installed and tried with success an older one (java 1.8).

**Comment by dgelessus** [comment] 2022-01-13 12:51
I'm able to reproduce this on both Windows 10 and 11 - ProB launches the parser, but its output goes into a new console window instead of being redirected to the ProB process like it should. This only happens if I use Oracle JDK 17 installed via the installer. Using the portable ZIP version of Oracle JDK 17, or with a different Java distribution like Eclipse Adoptium, ProB works as expected.

The problem is at least partially caused by SICStus Prolog. A similar process call in Python for example receives the output from Java without problems and does not open another console window:

```python
import subprocess
print(subprocess.call(["java", "-jar", "lib/probcliparser.jar", "-version"]))
# prints b"Version:    2.9.32\r\n..."
```

**Comment by dgelessus** [comment] 2022-01-13 12:58
Interestingly, even under SICStus, this only happens with specific combinations of `process_create` options. For example, this call reproduces the problem - a separate console window opens, and after closing it, Prolog prints `end_of_file`:

```prolog
:- use_module(library(process)).
repro :-
	process_create(
		path(java),
		['-jar', 'lib/probcliparser.jar', '-prolog', '-prepl'],
		[stdin(pipe(In)), stdout(pipe(Out)), stderr(pipe(Err))]
	),
	read_line(Out, Line),
	format("~s~n", [Line]).
```

But if I remove either the option `stdin(pipe(In))` or `stderr(pipe(Err))`, it works as expected - no console window appears, and Prolog prints the port number received from the parser.

**Comment by dgelessus** [comment] 2022-01-14 17:18
We contacted SICStus support about this - they were able to reproduce the underlying issue, and a fix is planned for the next bugfix release of SICStus.

Until the SICStus update is released and ProB is updated accordingly, the easiest workaround is to use a non-Oracle version of Java. Alternatively, you can manually add the Oracle Java bin directory (e. g. `C:\Program Files\Java\jdk-17\bin`) to your `PATH` environment variable.

(Background: Oracle Java already adds itself to the `PATH` by default, but it does so via intermediate "wrapper" EXE files that cause problems with SICStus. By manually adding the bin directory to the PATH, the "wrapper" EXE is bypassed, which avoids the SICStus incompatibility.)

Thank you for the bug report!

**Closed as completed by dgelessus** 2022-01-14 17:18 UTC
