### ISSUE TITLE
Show full value of entries in the ProB2-UI state view

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#283] opened 2023-01-24 12:58 UTC
When using "Show Value" in the State view one often only gets a shortened version of the value:

#3600:{(650↦500),(650↦501),...,(769↦528),(769↦529)}

It would be nice to have a "full value" option; possibly as a check box like the prettify option

**Comment by dgelessus** [comment] 2023-06-16 16:02
Duplicate of #93.

**Closed as not planned** 2023-06-16 16:03 UTC
Labels: enhancement, ProB2UI
