### ISSUE TITLE
Cannot enter semicolon in code editor

### ISSUE THREAD

**Issue by rutenkolk** [hhu-stups/prob-issues#106] opened 2022-02-09 10:45 UTC
Version tested:
Release 1.1.0

OS: WIN11
Keyboard Layout: German

Further System Details as per `systeminfo` :

```
Betriebssystemname:                            Microsoft Windows 11 Pro
Betriebssystemversion:                         10.0.22000 Nicht zutreffend Build 22000
Betriebssystemhersteller:                      Microsoft Corporation
Betriebssystemkonfiguration:                   Eigenständige Arbeitsstation
Betriebssystem-Buildtyp:                       Multiprocessor Free
Systemhersteller:                              To Be Filled By O.E.M.
Systemmodell:                                  To Be Filled By O.E.M.
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 158 Stepping 12 GenuineIntel ~3601 MHz
BIOS-Version:                                  American Megatrends Inc. P4.30, 12.08.2019
Windows-Verzeichnis:                           C:\WINDOWS
System-Verzeichnis:                            C:\WINDOWS\system32
Systemgebietsschema:                           de;Deutsch (Deutschland)
Eingabegebietsschema:                          de;Deutsch (Deutschland)
Zeitzone:                                      (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
Gesamter physischer Speicher:                  32.681 MB
Verfügbarer physischer Speicher:               21.932 MB
Virtueller Arbeitsspeicher: Maximale Größe:    37.545 MB
Virtueller Arbeitsspeicher: Verfügbar:         23.126 MB
Virtueller Arbeitsspeicher: Zurzeit verwendet: 14.419 MB
Auslagerungsdateipfad(e):                      C:\pagefile.sys
Domäne:                                        WORKGROUP
Hotfix(es):                                    4 Hotfix(e) installiert.
                                               [01]: KB5008880
                                               [02]: KB5004567
                                               [03]: KB5009566
                                               [04]: KB5007414
```

Expected Behavior: Typing `Shift` + `,` on a german keyboard should yield a `;` in the machine editor.

Behavior: Typing `Shift` + `,` on a german keyboard yields a `,` in the machine editor.

Interestingly a `;` *is* being typed when using Capslock.

**Comment by dgelessus** [comment] 2022-02-09 16:42
I can reproduce this with version 1.1.0, but not with the current snapshot. Since the last release we have updated the editor library that we use, to fix a different bug related to non-US keyboard layouts. Most likely this bug was also fixed in the same update.

**Closed as completed by dgelessus** 2022-02-09 16:42 UTC
Labels: bug, ProB2UI
