### ISSUE TITLE
ProB2-UI Show Full Value does not show full value

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#347] opened 2024-04-18 14:37 UTC
The description stops with ...
![Screenshot 2024-04-18 at 16 36 43](https://github.com/hhu-stups/prob-issues/assets/1742246/8f8940d3-53cb-4f71-b8dc-03456d7b7a2b)

**Comment by iTitus** [comment] 2024-04-18 15:13
same issue as #93
Caused by the the Kernel or Prolog I think:
> _but is still limited to 600 chars currently_

**Comment by iTitus** [comment] 2024-04-21 13:39
Fixed in dev, need a Prolog & Kernel release to use it in the UI

**Closed as not planned** 2024-04-21 13:47 UTC
Labels: bug, duplicate, ProB2UI, prob_prolog, prob2_kernel
