### ISSUE TITLE
State View shows variable as unchanged if pretty print stays unchanged

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#92] opened 2021-10-18 14:31 UTC
Depending on the MAX_DISPLAY_SET preference, larger sets are pretty printed in abbreviated from.
This can lead to the state view showing that there is no change in a variable after an operation,
even though the variable was changed.

**Comment by iTitus** [comment] 2024-04-21 13:50
Duplicate of #93

**Closed as not planned by iTitus** 2024-04-21 13:50 UTC
Labels: bug, duplicate, ProB2UI
