### ISSUE TITLE
Test case generation dialog resizing not ideal

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#43] opened 2021-03-02 12:56 UTC
Resizing the operation coverage test case generation dialog does not resize the tables:

![Screenshot 2021-03-02 at 12 21 13](https://user-images.githubusercontent.com/1742246/109651479-decc3800-7b5e-11eb-95b2-a37646b4ac44.png)

Also: the name of the command (Covered Operations Testing) should be changed.
Finally it is possible to select the number of the search depth but not change it with the keyboard.

**Comment by favu100** [comment] 2021-03-03 16:01
The Test Case Generation Input Stage should not be resizable. Furthermore, all Spinners should be editable now.

What is your suggestion for the new name of Covered Operations?

**Comment by yutak001** [comment] 2021-03-03 16:33
If the Test Case Generation Input Stage is not resizable my Linux computer seems to set the width and height of the stage to 0 or -∞ because I just get a nonresizable almost not visible* stage. 

*(1px in width)

**Comment by favu100** [comment] 2021-03-03 16:45
I've tried to fix it by invoking sizeToScene() before setting resizable to false. So, it is now solved in the code and not in the FXML file. Is the problem now solved on Linux?

**Comment by yutak001** [comment] 2021-03-08 10:09
Unfortunately no. It is still a window 1 px in width. Deleting the config file did not change anything either. :/

**Comment by favu100** [comment] 2021-03-09 14:18
https://bugs.openjdk.java.net/browse/JDK-8179073

This seems to be a known issue on Linux

**Comment by favu100** [comment] 2021-03-09 14:23
The Test Case Generation Dialog is now resizable. The whole content always fit to the dialog. Hopefully, the issue is fixed now. Reopen otherwise

**Closed as completed by favu100** 2021-03-09 14:23 UTC
Labels: enhancement, ProB2UI
