### ISSUE TITLE
Exception during SimB simulation

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#357] opened 2024-07-30 09:09 UTC
I got the following exception during a SimB (external) simulation:
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at de.prob2.ui.simulation.simulators.Simulator.createDynamicActivation(Simulator.java:161)
	at de.prob2.ui.simulation.simulators.Simulator.executeActivatedOperation(Simulator.java:302)
	at de.prob2.ui.simulation.simulators.Simulator.executeActivatedOperations(Simulator.java:256)
	at de.prob2.ui.simulation.simulators.Simulator.simulationStep(Simulator.java:220)
	at de.prob2.ui.simulation.simulators.check.SimulationCheckingSimulator.run(SimulationCheckingSimulator.java:272)
	at de.prob2.ui.simulation.simulators.check.SimulationCheckingSimulator.run(SimulationCheckingSimulator.java:232)
	at de.prob2.ui.simulation.SimulationItemHandler.lambda$runAndCheck$1(SimulationItemHandler.java:131)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by favu100** [comment] 2024-07-30 10:54
The problem is that the external simulation provides wrong information, i.e., wrong operation name to ProB. This error should be catched, and an error message should be shown accordingly

**Comment by favu100** [comment] 2024-08-01 07:26
This issue should be fixed now

**Closed as completed by favu100** 2024-08-01 07:26 UTC
Labels: bug, simb
