### ISSUE TITLE
Spurious errors at trace replay

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#134] opened 2022-05-03 11:41 UTC
When re-playing some traces in the Lading gear, certain problems occur:

Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦closed),(left↦closed),(right↦closed)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦extended),(left↦extended),(right↦extended)}
Error: Ignoring JSON value for parameter gr due to type or parse error: front
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦door_moving),(left↦closed),(right↦closed)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦open),(left↦closed),(right↦closed)}
Error: Ignoring JSON value for parameter gr due to type or parse error: left
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦open),(left↦door_moving),(right↦closed)}
Error: Ignoring JSON value for parameter gr due to type or parse error: right
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦open),(left↦door_moving),(right↦door_moving)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦open),(left↦open),(right↦door_moving)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦open),(left↦open),(right↦open)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦gear_moving),(left↦extended),(right↦extended)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦extended),(right↦extended)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦gear_moving),(right↦extended)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦retracted),(right↦extended)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦retracted),(right↦gear_moving)}
Error: Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦retracted),(right↦retracted)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦door_moving),(left↦open),(right↦open)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦door_moving),(left↦door_moving),(right↦open)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦closed),(left↦door_moving),(right↦open)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦closed),(left↦door_moving),(right↦door_moving)}
Error: Ignoring JSON value for parameter doors due to type or parse error: {(front↦closed),(left↦closed),(right↦door_moving)}

[INFO] ! Ignoring JSON value for parameter gears due to type or parse error: {(front↦retracted),(left↦retracted),(right↦retracted)}
[DEBUG] parse_error(parse_exception([pos(1,8,1,8,null)],'Invalid combination of symbols: \'front\' and \'\20646\\'. This keyword (front) must be followed by an opening parenthesis.\n')).
[DEBUG] parse_error(parse_exception([pos(1,5,1,5,null)],'Invalid combination of symbols: \'left\' before the end of file. This keyword (left) must be followed by an opening parenthesis.\n')).
[DEBUG] parse_error(parse_exception([pos(1,8,1,8,null)],'Invalid combination of symbols: \'front\' and \'\20646\\'. This keyword (front) must be followed by an opening parenthesis.\n')).
[DEBUG] parse_error(parse_exception([pos(1,6,1,6,null)],'Invalid combination of symbols: \'front\' before the end of file. This keyword (front) must be followed by an opening parenthesis.\n')).

It seems that, we should escape identifiers when storing the trace in the case they collide with an existing B keyword?

**Comment by dgelessus** [comment] 2022-05-03 12:05
Strange. Do you remember how you saved the trace? ProB 2 should use the `PrettyPrinter` from the B parser, which will quote identifiers if they conflict with keywords. The Prolog-side pretty printer does the same thing I think.

Maybe something is writing identifiers directly without going through a pretty-printer first?

**Comment by favu100** [comment] 2022-05-03 12:27
I have saved the trace in the History View of ProB2-UI

**Comment by dgelessus** [comment] 2022-05-03 12:46
It seems the problem is specifically for Event-B models. When saving the trace, probcli returns the variable values to ProB 2 in Event-B syntax, where `front` is a regular identifier. But when reading the trace back, probcli expects classical B syntax, where `front` is a keyword.

Unfortunately, I think ProB 2 cannot control which syntax is used for evaluation results - probcli always uses the syntax of the currently loaded model. Maybe we should change this so it's based on the syntax of the input formula - i. e. evaluating a `ClassicalB` formula would return classical B syntax, and evaluating `EventB` would return Event-B syntax.

Alternatively, maybe we should move the trace saving process to the Prolog side, like we've already done for the trace replay.

**Comment by leuschel** [comment] 2022-05-03 12:49
I think the trace file should probably always use classical B syntax in the JSON trace files; during replay the Prolog side does not have access to the Event-B parser.
We have already used this approach for VisB JSON files (there also to have access to external STRING functions).

**Comment by dgelessus** [comment] 2022-08-19 10:11
This should be fixed with hhu-stups/prob2_kernel@7715327ce214234e622a19ea50e5efcf7632d552 - ProB 2 now always uses classical B syntax when saving traces. This won't fix already saved trace files, but newly saved traces will work as expected.

**Closed as completed by dgelessus** 2022-08-19 10:11 UTC
Labels: bug, ProB2UI
