### ISSUE TITLE
Warning when loading a prob2trace in ProB2-UI

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#334] opened 2023-11-21 14:13 UTC
Sometimes, when replaying a saved `.prob2trace` in ProB2-UI, I get the following warning:
```
[INFO] ! A warning occurred (source: replay_json_trace_file) !
[INFO] ! JSON trace file model name Test.mch does not match current model name: Test
```
Unfortunately, I have not yet been able to reproduce it.

**Comment by iTitus** [comment] 2024-12-05 13:01
Closing because not reproduceable

**Closed as not planned by iTitus** 2024-12-05 13:01 UTC
Labels: ProB2UI, prob_prolog, cannot reproduce
