### ISSUE TITLE
Improve user feedback in operations view for events with MAX_OPERATIONS=0

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#369] opened 2024-10-10 11:37 UTC
When MAX_OPERATIONS is 0 for an event (e.g., using a DEFINITION like `MAX_OPERATIONS_comment == 0` for an event `comment(txt) = PRE txt:STRING THEN skip END`) then it would be nice not to show the red disabled icon in the operations view, but  maybe an orange or other icon to show that the event was not evaluated.
Alternatively, like in Tk, one could just evaluate the guards and show the red icon if the guard is false, and another icon (orange question mark) otherwise.

![Screenshot 2024-10-10 at 13 37 40](https://github.com/user-attachments/assets/57f710c0-b62b-4ce1-baa8-c4b41c04d7eb)

**Comment by cobizobi** [comment] 2024-10-25 12:26
I think this is a duplicate of #253.

**Closed as not planned** 2024-10-25 14:22 UTC
Labels: duplicate, enhancement, ProB2UI
